coverage:
  precision: 2
  round: down
  range: 25..30

  status:
    project:
      default:
        target: null
        treshold: null
    patch:
      default:
        target: null
        treshold: null
    changes: no

comment: 
  layout: "diff"
  behavior: once
