coverage:
  precision: 2
  round: down
  range: 25..30

  status:
    project:
      default:
        target: 0
        treshold: 0
    patch:
      default:
        target: 0
        treshold: 0
    changes: no

comment: 
  layout: "diff"
  behavior: once
  require_changes: no
