language: python
python:
  - 2.7
install:
    - make setup.py
    - pip install tox
env:
  - TOXENV=py27
matrix:
  fast_finish: true
  include:
    # - python: 3.5
      # env: TOXENV=lint
    - python: 2.7
      env: TOXENV=py27
script:
  - tox -e $TOXENV
cache: pip
